### ISSUE TITLE
Foto pony Games

### ISSUE THREAD

**Issue by mc-openstyle** [mc-openstyle/scuderiafiore#2]
Trovare 3 foto per sostituire quelle a destra
http://www.scuderiafiore.com/pony-games/

**Comment by Noemistambe** [comment]
![1239900044](https://cloud.githubusercontent.com/assets/13258857/8601470/8cc9e446-266c-11e5-945d-672fd238af40.jpg)
![600](https://cloud.githubusercontent.com/assets/13258857/8601471/8cce297a-266c-11e5-85f9-7ea5b422972d.jpg)
![620x400](https://cloud.githubusercontent.com/assets/13258857/8601469/8cc875d4-266c-11e5-8ad5-94cf4223ec6a.jpg)

**Comment by mc-openstyle** [comment]
modifica con 940*600

**Comment by Noemistambe** [comment]
![pony-club-games-practice-lrg-1024x768](https://cloud.githubusercontent.com/assets/13258857/8601830/ff295b6e-266e-11e5-9d79-ba9d6718ead7.jpg)
![p9](https://cloud.githubusercontent.com/assets/13258857/8601832/ff2dbc0e-266e-11e5-8589-fef06e974a21.jpg)
![pony-club-games-zone-finals-2011-199](https://cloud.githubusercontent.com/assets/13258857/8601831/ff2d43e6-266e-11e5-9c92-a3f6249ef4a4.jpg)
