### ISSUE TITLE
Pensione Cavallo

### ISSUE THREAD

**Issue by mc-openstyle** [mc-openstyle/scuderiafiore#4]
http://www.scuderiafiore.com/servizi/pensione-cavallo/ 3 immagini 940*600

**Comment by Noemistambe** [comment]
![20130315_171417](https://cloud.githubusercontent.com/assets/13258857/8602461/b83a5f4c-2672-11e5-92f8-143448692a54.jpg)
![dscn5279](https://cloud.githubusercontent.com/assets/13258857/8602460/b837950a-2672-11e5-8514-ac6e384a8090.JPG)
![img_0413](https://cloud.githubusercontent.com/assets/13258857/8602462/b83dace2-2672-11e5-93e5-cfe98001b03f.JPG)
