### ISSUE TITLE
naturalizzazione

### ISSUE THREAD

**Issue by mc-openstyle** [mc-openstyle/scuderiafiore#6]
3 immagini su piede scalzo 940*600 
http://www.scuderiafiore.com/servizi/naturalizzazione/

**Comment by Noemistambe** [comment]
![20150308_113519](https://cloud.githubusercontent.com/assets/13258857/8602815/b83c84e6-2674-11e5-9171-5b6436f29129.jpg)

**Comment by Noemistambe** [comment]
![20150308_112837](https://cloud.githubusercontent.com/assets/13258857/8602900/2b2cb458-2675-11e5-8aef-562dd8079daf.jpg)
![20150308_113519](https://cloud.githubusercontent.com/assets/13258857/8602899/2b2c34e2-2675-11e5-8b3d-edf344e0d8a4.jpg)
