### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mc-openstyle** [mc-openstyle/scuderiafiore#7]
![logo finale](https://cloud.githubusercontent.com/assets/10564549/8601627/7cbfb548-266d-11e5-8b4f-d573de8acd11.jpg)
portalo con altezza 60px

**Comment by Noemistambe** [comment]
![senza-titolo-1](https://cloud.githubusercontent.com/assets/13258857/8603153/a761a9ce-2676-11e5-915c-0c3874fad0c8.jpg)
![logo-finale](https://cloud.githubusercontent.com/assets/13258857/8603154/a766fb86-2676-11e5-8ad6-3bf21f2045d9.jpg)

**Comment by Noemistambe** [comment]
![senza-titolo-1](https://cloud.githubusercontent.com/assets/13258857/8603238/45fe4b00-2677-11e5-97d2-0512f8a6c150.jpg)
![logo-finale](https://cloud.githubusercontent.com/assets/13258857/8603237/45fc6d62-2677-11e5-9790-e9f7879511d5.jpg)

**Comment by mc-openstyle** [comment]
togli passione per il cavallo come scritta e scrivi scuderia fiore più grande a dx del logo

**Comment by Noemistambe** [comment]
![senza-titolo-1](https://cloud.githubusercontent.com/assets/13258857/8603468/baedca34-2678-11e5-9f2d-f888c0af4612.jpg)
